name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸš€ Features'
    label:
      - 'feature'
      - 'infra'
  - title: 'ğŸ› Hotfixes'
    labels:
      - 'fix'
  - title: 'ğŸ”§ Maintenance'
    labels:
      - 'docs'
      - 'refactor'
      - 'test'
      - 'docs'
      - 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES